# Generated by Django 5.2.7 on 2025-11-23 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0003_eventoexpediente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR', 'Pago QR'), ('PASARELA', 'Pasarela (Stripe)')], default='EFECTIVO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('transaccion_id_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='casos.caso')),
                ('concepto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.conceptopago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=50, unique=True)),
                ('nit_ci', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=150)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('codigo_control', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='finanzas.pago')),
            ],
        ),
    ]
