# Generated by Django 5.2.7 on 2025-11-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR', 'Pago QR'), ('TARJETA', 'Pasarela (Stripe)')], default='EFECTIVO', max_length=20),
        ),
    ]
